############################ Default configuration #########################

baseURL: "https://eclipse.dev/sumo"
languageCode: "en-us"
title: "Eclipse SUMO - Simulation of Urban MObility"
disableKinds: ["taxonomyTerm"]
theme: "sumo-theme"
enableGitInfo: true

########################### Default Parameters #############################

frontmatter:
  lastmod:
    - lastmod
    - :git
    - date

params:
  favicon: "images/favicon.ico"
  logo: "images/logos/sumo-logo-white.svg"
  docsURL: "https://sumo.dlr.de/docs"
  githubEditURL: "https://github.com/eclipse-sumo/sumo.website/edit/source/content/"
  Version: "1.25.0"
  DOI: "10.5281/zenodo.17594250"

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
