############################ Default configuration #########################

baseURL: "https://www.eclipse.dev/sumo"
languageCode: "en-us"
title: "Eclipse SUMO - Simulation of Urban MObility"
disableKinds: ["taxonomyTerm"]
theme: "sumo-theme"
#enableGitInfo: true

########################### Default Parameters #############################

params:
  favicon: "images/favicon.ico"
  logo: "images/logos/sumo-logo-white.svg"
  docsURL: "https://sumo.dlr.de/docs"
  githubEditURL: "https://github.com/eclipse-sumo/sumo.website/edit/main/content/"
  Version: "1.18.0"

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 1
