name: trigger_deploy

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: eclipse-sumo/sumo.website/.github/workflows/deploy.yml@source
    permissions:
      contents: write
      actions: write
